apiVersion: v1
kind: Pod
metadata:
  name: jupyter-pod
spec:
  containers:
  - name: jupyter
    image: jupyter/base-notebook:latest
    ports:
    - containerPort: 8888
    volumeMounts:
    - mountPath: /home/jovyan/work
      name: notebooks-volume
    env:
    - name: JUPYTER_TOKEN
      value: ":)secure_token"  # Set a Jupyter token for access
  volumes:
  - name: notebooks-volume
    hostPath:
      path: ./notebooks  # Path to the local directory for the notebooks
      type: Directory
